### ISSUE TITLE
非管理员启动的情况下不会输出提示，和一些问题与建议

### ISSUE THREAD

**Issue by huiyadanli** [Alex-Beng/Yap#1]
拿来抓晶蝶测试了一番，**非常好用**。

以下是我的一些使用反馈，不懂 Rust，如果下面内容我的理解有问题也请指出

## 测试非管理员启动的情况下没有提示

看了下代码应该是有的

https://github.com/Alex-Beng/Yap/blob/cb86063704e2c3ef1d3eccee5c09a1a08e06de22/src/main.rs#L38-L40

个人使用的时候直接把下面内容保存为start.bat，丢到Yap目录下方便以管理员权限和自己想要的参数启动程序

```cmd
@echo off
cd /d "%~dp0"
cacls.exe "%SystemDrive%\System Volume Information" >nul 2>nul
if %errorlevel%==0 goto Admin
if exist "%temp%\getadmin.vbs" del /f /q "%temp%\getadmin.vbs"
echo Set RequestUAC = CreateObject^("Shell.Application"^)>"%temp%\getadmin.vbs"
echo RequestUAC.ShellExecute "%~s0","","","runas",1 >>"%temp%\getadmin.vbs"
echo WScript.Quit >>"%temp%\getadmin.vbs"
"%temp%\getadmin.vbs" /f
if exist "%temp%\getadmin.vbs" del /f /q "%temp%\getadmin.vbs"
exit

:Admin

yap.exe --log info
```

## 甜甜花的种子识别错误

不在黑名单内，也不会拾取。

![image](https://github.com/Alex-Beng/Yap/assets/15783049/62e9b611-ecdd-4427-8b12-f5583bc021dc)

![image](https://github.com/Alex-Beng/Yap/assets/15783049/c59ec084-4a69-44be-8f92-28f896536472)

## 对于单个物品的情况下，速度是否还能优化？

如果对于晶蝶这种，自动能够F住一闪而过的晶蝶就好了

大致看了下 [pickupper.rs](https://github.com/Alex-Beng/Yap/blob/master/src/pickupper/pickupper.rs)，默认好像会获取5块区域进行推理，但是实际看好像对速度影响也不大。

**Comment by Alex-Beng** [comment]
# 感谢反馈！

# 管理员权限

这段代码是抄yas的，实际是我并不确定需不需要管理员权限，在我电脑上直接双击也能运行。


如果真的需要管理员权限，像你那样使用`.bat`来检测和获取管理员权限，确实是一个不错的方案。


# 甜甜花种子识别

查了下，是训练的时候没加进去大名单`all_list`，需要拾取的逻辑如下

https://github.com/Alex-Beng/Yap/blob/cb86063704e2c3ef1d3eccee5c09a1a08e06de22/src/pickupper/pickupper.rs#L268-L270

这个`all_list`的json文件是yap-train仓库中[export_all_list.py](https://github.com/Alex-Beng/yap-train/blob/4cc792c9bf7b0d188d6155680b9fb59bccca96ec/export_all_list.py)导出的，实际上就是训练时的词库。

PS：简单来说就是词库不全，还要再训练一下

# 单个物品的速度


这一点我也有所感知，之前的单区域策略对于单个物品，夜兰E路过也能捡起来，现在是5区域策略，推理速度大概是x5（测试过一个推理tensor五张图片 vs 五个一张图片tensor的推理，差距在几个ms上且交替领先），这里相比单区域策略慢了约20ms。

这个确实是问题，早期版本的是单区域策略，即只推理F键指向的文字，如果是就捡，然后向下滚。导致了需要一个状态机去控制再往上翻，然后这个状态机写的太抽象了（可以去参观早期版本的pickupper，丑的惊人），导致在只有一个物品，且是黑名单的时候（例如秘境），会致使视角不断拉近拉远。

当时想的策略是去感知多个text，就可以比较完全地避免这个上下翻动的问题了，且在多个拾取物时无需多次寻找F键了，因为寻找F键是关键路径。

F键检测在我机器上基本是`50~60ms`，几乎是推理时间的2-3倍。使用模板匹配的的原因是参考了GIA。

我目前想法是使用轻量级的目标检测网络，将时间优化到10ms左右。

PS： 如果对单物品速度有要求，可以尝试使用v0.1.5之前的yap，然后调优一下`infer-gap`。

如果你有什么比较好的方案，欢迎交流。

**Comment by Alex-Beng** [comment]
经过一晚上的学习，认识种子了。

![屏幕截图 2023-08-05 235120](https://github.com/Alex-Beng/Yap/assets/30763045/821cd388-32ff-46c8-9785-69852f3bc86e)

**Comment by huiyadanli** [comment]
感谢优化~

另外管理员权限这块是必须的，因为原神是以管理员权限启动的，没有管理员权限没法直接给原神发送键盘消息控制
