### ISSUE TITLE
打开后报错

### ISSUE THREAD

**Issue by blaze1999** [Alex-Beng/Yap#12]
![屏幕截图(47)](https://github.com/Alex-Beng/Yap/assets/26127025/fdf6cc86-a289-4502-8e28-73e0e3d4b870)

**Comment by blaze1999** [comment]
Failed to register hotkey
这是有什么快捷键占用了，所以打不开吗？

**Comment by Alex-Beng** [comment]
大概率是别的应用也注册了这个hotkey组合，这个hotkey是通过windows api注册的。

**Comment by Alex-Beng** [comment]
目前拾取时序也比较稳定，后面默认干掉算了，调试再打开

**Comment by Alex-Beng** [comment]
默认不开启除了ALT+F和ALT+B只外的hotkey，见release的15-alpha。如果未解决请回复

**Comment by blaze1999** [comment]
谢谢，我找了挺久，关了挺多软件，也不知道 是什么键占用了

**Comment by Alex-Beng** [comment]
> 谢谢，我找了挺久，关了挺多软件，也不知道 是什么键占用了

所以15-alpha解决问题了嘛

**Comment by blaze1999** [comment]
可以运行了，非常感谢。。是否可以以python的方式来运行啊？

**Comment by Alex-Beng** [comment]
可是这个项目的一个出发点就是为了避免python配置环境的下载，以及获得更加极致的性能。。
