### ISSUE TITLE
未加入黑名单的NPC都会自动对话

### ISSUE THREAD

**Issue by blaze1999** [Alex-Beng/Yap#13]
未加入黑名单的NPC都会自动对话，是否需要把所有的NPC名字加一遍才能防止对话呢？
实际上这类NPC的对话框在F的右边都会有省略号。
![屏幕截图(48)](https://github.com/Alex-Beng/Yap/assets/26127025/99faa05d-d9cd-423b-8919-b401af9ec8bc)

    "快拳阿凌",
    "霹雳闪雷真君",
这俩人名字真好笑

**Comment by Alex-Beng** [comment]
可是默认的黑名单已经把（我已知）的npc和交互都加进去了

https://github.com/Alex-Beng/Yap/blob/f72dd322bd766e15ea9b41b12001e5f973eff0da/black_lists.json#L362-L363
