### ISSUE TITLE
请问下这个是什么错误

### ISSUE THREAD

**Issue by Yukikaze1718** [Alex-Beng/Yap#14]
![Uploading 1222.png…]()

**Comment by Alex-Beng** [comment]
你图片没传上来

**Comment by Yukikaze1718** [comment]
![Uploading 1222.png…]()

**Comment by Alex-Beng** [comment]
![image](https://github.com/Alex-Beng/Yap/assets/30763045/998fb414-5196-4d66-9f3a-1b4e08b057d5)
你复制图片进来得等它上传好，，

**Comment by Yukikaze1718** [comment]
![1222](https://github.com/Alex-Beng/Yap/assets/144823495/54090820-8cac-4b26-8672-c2e6977af5cd)

**Comment by Alex-Beng** [comment]
这个问题别人也提过，他是0.1.12版本能用，14就有这个问题。你可以试一下能不能复现。这两个版本运行到你这个报错前只改了默认参数，所以我也不知道为什么。此外可以试一下15-alpha。

**Comment by Yukikaze1718** [comment]
我前天用13版本可以正常的运行，今天跟新了14就有这个问题，换回13又变成hotkey的错误，用15倒是没问题

**Comment by Alex-Beng** [comment]
hotkey的一个问题可能是同时运行了两个yap，

**Comment by Alex-Beng** [comment]
或者是其他应用注册了用windows api同样的快捷键。

**Comment by Alex-Beng** [comment]
13到14也是也是只改了硬编码的默认参数，玄学起来了

**Comment by Yukikaze1718** [comment]
我试了下，只要运行过更高级的版本，之前的版本都会出现hotkey的错误

**Comment by Alex-Beng** [comment]
你确定之前运行的yap彻底关闭了嘛，显示`摁Enter关闭`属于还没关闭。

**Comment by Yukikaze1718** [comment]
应该是彻底关闭了吧，我在任务管理器里面关掉了，又重启了电脑还是一样的
