### ISSUE TITLE
4.1的新掉落物不能自动捡

### ISSUE THREAD

**Issue by blaze1999** [Alex-Beng/Yap#15]
4.1的新掉落物不能自动捡。
这个有新的物品也需要更新程序的么？是不是有一份可捡物品的列表的？

**Comment by Alex-Beng** [comment]
需要重新训练模型，要花点时间

**Comment by blaze1999** [comment]
好奇怪。。。我一直以为是通过图片识别文字的。
4.1就是多出来了新的物品，文字不一样了吧？为什么需要训练哦，想不通想不通～

**Comment by Alex-Beng** [comment]
因为不是用所有汉字进行训练的，是使用会出现的词来训练，所以新材料、新操作、新掉落物啥的可能会多了不认识的字，认识的字可见[index_2_word.json](https://github.com/Alex-Beng/Yap/blob/d2f0911c8ddafb33188b99dcf038d39cc3d13a35/models/index_2_word.json)，目前也才1765个字（含空白）。再加上一些零零碎碎的词和4.1的词，目前应该是1771个字。

就算新的词都由模型已经认识的字构成，也会因为归纳偏置（这里表现为我更喜欢用出现的词，而不是会出现的字的分布来进行训练）导致识别不稳定。

至于为啥不按字训练，只能说我试过，效果并不好，体现在精度和训练时长上。

**Comment by Alex-Beng** [comment]
总结就是，不能仅更新可捡物品的列表实现，还需要微调模型，甚至是更改模型结构（加了新字）再微调

**Comment by blaze1999** [comment]
谢谢耐心解释~~非常专业
