### ISSUE TITLE
强化圣遗物功能用不了？

### ISSUE THREAD

**Issue by htshts1115** [Alex-Beng/Yap#16]
在圣遗物强化界面，alt+b 命令行显示打开了这个功能，但是会切出游戏界面（比如切到了桌面），再点回去就没有任何动作了

我是2560*1440 无边框窗口化，125%缩放

**Comment by Alex-Beng** [comment]
是有这个问题，还没修。

鼠标移动和点击的位置是在1080p下面得到和测试的，所以在1080p下是能用的。

其他更小的的16:9的分辨率也会出现奇怪的位置，导致点击位置超出界面，就会切到其他窗口/桌面。

**Comment by Alex-Beng** [comment]
这个问题是代码把x y对应的窗口偏置加反了。

所以并不是1080p能用，而是全屏1080p能用，此时x y偏置均为0。

目前已修复。

**Comment by htshts1115** [comment]
> 这个问题是代码把x y对应的窗口偏置加反了。
> 
> 所以并不是1080p能用，而是全屏1080p能用，此时x y偏置均为0。
> 
> 目前已修复。

我在0.1.16版本还是不行，2560*1440 无边框窗口化（屏幕分辨率3440*1440），125%缩放

**Comment by Alex-Beng** [comment]
因为是在16版本之后的commit修的，没有更新到release

**Comment by Alex-Beng** [comment]
tag 17-beta已修复

**Comment by htshts1115** [comment]
我这边测试还是有点问题，看起来操作流程是：快捷放入-升级-切换到详情-切回升级，但是可能切回来太快了，没有跳过升级动画

**Comment by Alex-Beng** [comment]
看来得加入修改。https://github.com/Alex-Beng/Yap/issues/11 考虑将各种时序、黑白名单及其他参数整合到一个大的config文件吧，然后命令行参数也能简化

**Comment by Alex-Beng** [comment]
目前在v0.1.17里简单地把delay × 2了

**Comment by htshts1115** [comment]
我试了好像不太稳定，有时候还是会出动画

**Comment by Alex-Beng** [comment]
那就别用了，，本来也不是正经功能

**Comment by htshts1115** [comment]
我自己编译了，用300ms 可以稳定工作

**Comment by Alex-Beng** [comment]
可以提个pr。后面有空再写个从config读的吧

**Comment by Alex-Beng** [comment]
下一个版本官方会有快速强化的实现，这个也不用维护了。
