### ISSUE TITLE
存在放Q大招时，自动停止脚本的可能性

### ISSUE THREAD

**Issue by blaze1999** [Alex-Beng/Yap#18]
当PC端使用alt + 1，2，3，4 放大招的时候，同时又出现了掉落物时，脚本会自动按F,
这个时候就会出现自动 alt + F 触发停止自动捡物的可能性。有没有可能这个功能换个不容易触发的组合键呢？

**Comment by Alex-Beng** [comment]
原来有时候alt+f关脚本的时候会触发多次也是这个问题

**Comment by blaze1999** [comment]
还有我alt + tab切换有时候也会触发alt + f
也许 ctrl + = 这种会更好

**Comment by htshts1115** [comment]
> 用alt+f是因为gis也是这个快捷键，不知道改成啥，，，

我也在用gis，为什么要和它设成一样的呢？

**Comment by Alex-Beng** [comment]
> > 用alt+f是因为gis也是这个快捷键，不知道改成啥，，，
> 
> 我也在用gis，为什么要和它设成一样的呢？

因为我不用gis

**Comment by Alex-Beng** [comment]
dev 分支里改成alt+0了

**Comment by Alex-Beng** [comment]
tag 17-beta通过更改为alt+0修复了
