### ISSUE TITLE
windows 显示缩放不能适配

### ISSUE THREAD

**Issue by htshts1115** [Alex-Beng/Yap#2]
我使用125%缩放就不能正常使用，test.png显示截图偏移了
改为100%缩放就正常了。但是高分屏100%缩放太小了……
请支持缩放，谢谢！
![image](https://github.com/Alex-Beng/Yap/assets/18262906/9b77660f-e2ff-4b4a-91c7-cbd28bd852f8)

**Comment by Alex-Beng** [comment]
未复现问题，能提供一下test.png嘛。

**Comment by htshts1115** [comment]
![test](https://github.com/Alex-Beng/Yap/assets/18262906/3b7b2af9-bbeb-4b9d-9468-481801d8635e)
这是125%缩放 1920*1080

**Comment by Alex-Beng** [comment]
似乎是gdi截屏的问题，修复后可能需要你协助一下测试，我屏幕都是1080p，测试不了

**Comment by Alex-Beng** [comment]
复现了，双屏设置缩放设置到另一个屏幕上了。

**Comment by Alex-Beng** [comment]
已经将修复commit到主分支，同时发布了一个[Pre-release](https://www.github.com/Alex-Beng/Yap/releases/tag/v0.1.11_alpha)。

**Comment by Alex-Beng** [comment]
服了，yap会从api查tag导致yap崩了，先改下tag名

**Comment by Alex-Beng** [comment]
> 服了，yap会从api查tag导致yap崩了，先改下tag名

《修了修复bug的bug》
