### ISSUE TITLE
交互文字识别相关的探讨

### ISSUE THREAD

**Issue by huiyadanli** [Alex-Beng/Yap#20]
首先，感谢您开源了这么好用的软件，并提供详尽的文档与说明。

我阅读了几乎所有的 Yap 的代码并把 Yap 的文字识别模型集成到了自己的原神[自动化的项目](https://github.com/babalae/better-genshin-impact)中。

在开发与测试过程中，我这边也有一些方案，效果不一定好，想要与您进行探讨下是否可行。

## 文字二值化

在测试过程中发现背景部分区域较浅的时候会影响 otsu 二值化的表现（我看现在已经改为灰度图:joy:）

https://github.com/Alex-Beng/Yap/blob/40f3a42b0f244a767e981acfea51bb84e2bfc807/src/pickupper/pickupper.rs#L220-L226

个人觉的理想的解决方案是使用 自适应阈值(Adaptive Threshold) 来进行二值化。

OpenCV文档：https://docs.opencv.org/4.x/d7/d4d/tutorial_py_thresholding.html

以下是我这边的结果比较

OSTU:

![1](https://github.com/Alex-Beng/Yap/assets/15783049/ec12c7b2-ba82-4c68-ae64-aba0c182e822)

Adaptive Threshold:

![2](https://github.com/Alex-Beng/Yap/assets/15783049/0dba2059-0159-4262-9fa9-96f2f4815e3c)
![31](https://github.com/Alex-Beng/Yap/assets/15783049/7964a729-d0b9-429e-89c6-9f997dc0a1d8)

但实际 OSTU 识别文字的结果更好。

## NPC或者交互物的黑名单排除

个人用了多次模板匹配图标的方式排除了NPC相关的交互。性能上肯定有所损失，但是准确度会上升。

大致流程

1. 找到 F 键的位置 ![F](https://github.com/Alex-Beng/Yap/assets/15783049/aefdf494-e8d5-47d5-97b1-40a32e4a52b9)
2. 往右进行固定图像的切割（ROI），拿到感兴趣的图标区域
3. 在图标区域进行模板匹配，排除 设置图标  ![settings](https://github.com/Alex-Beng/Yap/assets/15783049/6835e883-74ff-4d18-b4c0-ea8214a4e072) 和 聊天气泡 ![option](https://github.com/Alex-Beng/Yap/assets/15783049/a9084c50-7762-45b4-b67b-85eebe2d73c6) 图标

这样可以快速排除大量黑名单内容。

## 最后

在测试 Yap 、和阅读文档的过程中，我发现交互关键词的采集还是比较困难。这边有一份截止 4.0 的所有NPC名称列表（已去重，来自于解包），希望能帮助到您。

[npc.txt](https://github.com/Alex-Beng/Yap/files/13197855/npc.txt)

**Comment by Alex-Beng** [comment]
非常感谢您的认可及支持！！！

我也按点来说吧。

# 二值化

目前已经直接使用灰度了，所以所有二值化的劣势：如导致不全/甚至完全错误的问题已经解决。

adaptive threshold也尝试过，刚好就是你截出来里的注释掉的代码。效果感觉跟ostu差不多，也会出现缺字的现象，尽管肉眼可以看到分割出了字的轮廓，其还是被背景比较紧密的包围，这样的阈值结果对于之前使用阈值预处理的模型来说，如果不引入真实数据也是无法处理的，因为生成数据做不到这种包围，模型学不到。

此外，基于阈值的预处理很难避免缺字吧，，所以灰度已经杀死了比赛，见https://github.com/Alex-Beng/Yap/issues/4

https://github.com/Alex-Beng/Yap/blob/40f3a42b0f244a767e981acfea51bb84e2bfc807/src/pickupper/pickupper.rs#L220-L226

# 黑名单

本项目里的模板匹配是有缺点的，1. 没有使用mask，带来了噪声。2. naive实现，没有例如opencv实现里的simd加速。

而且有些词也不是同一个类别。 对于`调查`，这个我放入白名单的，并不全是调查点，部分是进入对话。所以这个点，乃至比较通用的目标检测是需要做的。

在考虑基于轮廓（需要阈值，这里对于固定大小的的东西用adaptive threshold效果应该要比otsu好，可以设置邻域）+手工特征（如轮廓矩啥的）去识别各种东西，以避免naive实现的模板匹配耗时过大的问题。可见https://github.com/Alex-Beng/Yap/issues/6

当然，另一条路是自己写一个simd的模板匹配加速。此外还尝试了一些基于目标检测神经网络的方法。可见[yap-train](github.com/Alex-Beng/yap-train)中的eula/部分。

目前想法是想找到一种比较通用的方案，例如基于轮廓/基于神经网络（刚好对应了比较经典的cv和现代cv），模板匹配也是可以考虑的，但是对于目前的rust来说要实现1. 带mask 2. simd加速，似乎需要手搓轮子。（主要还是时间的问题）


# 名单

我在3.6的server leak里面也提取了好多，可见

https://github.com/Alex-Beng/yap-train/blob/c6ce4f6647833aacaccea7ac16078fb9a2e37540/mona/text/server_leak_names.py

目前来看，您提供的npc.txt名单里缺少了649个，还需要筛掉一些奇奇怪怪的词并分类，方便交流一下怎么解包嘛，我这边是按词的出现方式分类的，您提供的是混在一起的，如`"进入内室"`这种并不算npc（在我的分类里）。

```
"#{NICKNAME}",
"#{REALNAME[ID(1)|HOSTONLY(true)]}",
"(Test)平原料理任务NPC",
"(Test)捕鱼挑战NPC",
"(Test)星火",
"(Test)桥西",
"(Test)漂流瓶收集者",
"(Test)索拉雅",
"(Test)车夫",
"(test）拳手一号",
"(test）盗宝团电",
"(test）镜头",
"???",
"NPC动作测试1-男",
"NPC动作测试2-女",
"NPC动作测试3-女",
"PhatomSamurai",
"test伪装的千岩军1",
"test伪装的千岩军2",
```

# 最后

目前处于疯狂赶毕设的状态，时间会比较少花在这个项目上。:-(

**Comment by huiyadanli** [comment]
感谢回复！

1. 我自己截取的代码居然没看到已经尝试过  adaptive threshold，原来已经尝试过了，大意了:joy:
2. 这就切换灰度的方案并使用新的模型，再次感谢！
3. 相比 server leak 这个NPC名单应该新增了 1817 个交互项（不一定是NPC，但是大部分是NPC，如果不是的话也应该是交互项），部分人名我看了下确实不存在。
