### ISSUE TITLE
快速拾取物品时会出现视角缩放鼠标滚轮滑动效果

### ISSUE THREAD

**Issue by EHZZZ** [Alex-Beng/Yap#24]
rt，0.21版本快速拾取物品模拟鼠标滚轮滑动，快速移动会让视角放大，快速切地图会出现地图缩放。
请问这个有办法解决或者优化吗？

**Comment by Alex-Beng** [comment]
没啥办法优化。

如果是多个可拾取的，不会有这个问题，如果都是不拾取的而且很多，就会触发多次滚轮向下查找可拾取的，因为新出现的拾取物是出现在下方的。

此外，这个向下滚动yap最多只**连续向下两次**，因为yap目前最多感知当前F key上下共五个文字区域，所以默认会滚到最下面的时候，最多也是两次滚动。注意是不是还有其他工具触发了滚动。而且，如果检测到以及最下面就不会再触发滚动了。

**Comment by EHZZZ** [comment]
懂了，感谢您的回复。
这软件让我摆脱了锄地尾气的局面，另外有个请求能否加个自动点传送的功能，就手动点击传送瞄点后检测固定坐标像素值变化，然后自动点击传送，最好是有个快捷键或者在config里配置开关。当然这只是我个人建议，我没接触过rust不清楚实现上会有什么问题。

**Comment by Alex-Beng** [comment]
希望你能理解，作为一个识字的拾取器，各种其yin他cang功能肯定不会使用像素这种级别的感知。
例如，yap有个功能是联机邀请/进入世界自动摁Y，也是通过识别上方区域的字去做的。

yap的方案可能是基于轮廓+轮廓特征的方案，可以做到μs级别的定位。

feat: 传送锚点点击。

**Comment by Alex-Beng** [comment]
增加了传送/确认的点击。可使用[nightly-22](https://github.com/Alex-Beng/Yap/releases/tag/nightly-22)帮忙验证是否有问题。

**Comment by EHZZZ** [comment]
光速啊，感谢已经在用了，目前暂未发现问题

**Comment by EHZZZ** [comment]
反馈个问题，追踪任务的时候会被识别为传送一直点击

**Comment by Alex-Beng** [comment]
推广到更广义的UI识字任务 #27
