### ISSUE TITLE
右下角的遮罩挡住我点地图

### ISSUE THREAD

**Issue by blaze1999** [Alex-Beng/Yap#29]
这个右下角的遮罩，居然会挡住我点地图。。。反正就是那一块被盖住了，不能鼠标点按了。。。这个遮罩能关掉吗？

**Comment by Alex-Beng** [comment]
可以移开的

**Comment by EHZZZ** [comment]
能给配置项关闭吗？像加世界自动按Y这些功能用不上的，想全加配置里面自定义开关。

**Comment by Alex-Beng** [comment]
nightly-39已添加Y和uid mask的配置。
