### ISSUE TITLE
nightly-37 bug 

### ISSUE THREAD

**Issue by revy-git** [Alex-Beng/Yap#30]
![image](https://github.com/Alex-Beng/Yap/assets/111768965/83d2317d-7f29-4513-8269-f45991d6d689)
```
{
  "black_list": [
  "混沌枢纽"
  ],
  "white_list": [],
  "f_gap": 85,
  "f_internal": 50,
  "infer_gap": 55,
  "scroll_gap": 70,
  "pick_key": "g",
  "click_tp": true,
  "cos_thre": 0.9977
}
```

**Comment by Alex-Beng** [comment]
there is an app has registered ALT+Z hotkey in Windows. This combination used before for on/off pick, idk which app will register it.

**Comment by revy-git** [comment]
> there is an app has registered ALT+Z hotkey in Windows. This combination used before for on/off pick, idk which app will register it.
"NVIDIA Geforce Experience" default hotkey

**Comment by Alex-Beng** [comment]
got it.

**Comment by Alex-Beng** [comment]
change it to alt+8
