### ISSUE TITLE
新版本是否会自动同意组队？

### ISSUE THREAD

**Issue by blaze1999** [Alex-Beng/Yap#34]
新版本是否会自动同意组队了？
比如雷神本我在偷矿。。。然后1p发出打boss邀请，以前界面最上面会弹出一个Y的窗口。现在是会直接弹出是和拒绝~

**Comment by Alex-Beng** [comment]
默认开启，要关掉在config.json里面加    "press_y": false

**Comment by blaze1999** [comment]
{
  "black_list": [
    "不祥的面具",
    "黑晶号角",
    "黑铜号角",
    "地脉的枯叶",
    "地脉的新芽",
    "混沌炉心",
    "混沌回路",
    "雾虚灯芯",
    "雾虚草囊",
    "督查长祭刀",
    "特工祭刀",
    "攫金鸦印",
    "石化的骨片",
    "结实的骨片",
    "混沌枢纽",
    "隐兽利爪",
    "何人所珍藏之花",
    "外世突触"
  ],
  "white_list": [
    "挖掘",
    "湖光铃兰",
    "调查"
  ],
  "press_y": false,
  "uid_mask": false
}

我这样设置了，但还是无效，版本是yap0.2.1的exe版本。

**Comment by Alex-Beng** [comment]
用新一点的nightly，应该是nightly-40之后有的
