### ISSUE TITLE
自动请求admin权限

### ISSUE THREAD

**Issue by Mikachu2333** [Alex-Beng/Yap#37]
RT。
在我的fork上面鼓捣了一个分支，不过一直编译失败……不知是不是gnu套件的锅……

参考资料：

https://docs.rs/winres/0.1.12/winres/struct.WindowsResource.html

https://stackoverflow.com/questions/53846395/how-do-i-set-the-windows-execution-level-to-ask-user-for-administrator-privilege

**Comment by Alex-Beng** [comment]
#39
