### ISSUE TITLE
是否需要减小项目体积

### ISSUE THREAD

**Issue by Mikachu2333** [Alex-Beng/Yap#41]
如果需要可以把winres换为 https://github.com/nabijaczleweli/rust-embed-resource

**Comment by Mikachu2333** [comment]
缺点：不能写文件版本啥的了

优点：稍小，可自动管理员

**Comment by Alex-Beng** [comment]
release 出来好像都是9M的压缩包

**Comment by Alex-Beng** [comment]
加了winres

**Comment by Mikachu2333** [comment]
也是，问题还不大
