### ISSUE TITLE
词条有很多重复是特性还是bug？

### ISSUE THREAD

**Issue by Mikachu2333** [Alex-Beng/Yap#55]
如题
![图片](https://github.com/user-attachments/assets/bc9b53aa-b178-4549-98df-e1aa0466bfeb)

**Comment by Mikachu2333** [comment]
还有不少什么黄麻子众人啥的，如果重复词条没啥用的话建议用python去个重看看

**Comment by Alex-Beng** [comment]
训练的时候想着让它出现概率高一点，然后随手复制的。

运行时是到同一个name2pickle的映射，不会影响就是了，，

https://github.com/Alex-Beng/yap-train/blob/18e5cb33ac2e11e16ab5cbd8611f1e06b1b376d9/mona/text/server_leak_names.py#L1359

（训练那边弄个脚本扫一下也行，

**Comment by Mikachu2333** [comment]
那没事了，只是因为自己在车原神字典……

真・纯手工校对……
