### ISSUE TITLE
黑名单列表能支持正则表达式吗？

### ISSUE THREAD

**Issue by SheldonWxy** [Alex-Beng/Yap#57]
黑名单列表能支持正则表达式吗？会影响识别性能吗？
例如：
```py
for(_blackName : _blackList){
    if(re.match(_blackName, text))
        return;
}
```

**Comment by Alex-Beng** [comment]
能支持。但是我能想到唯一一个场景是陈哥壶里面的种植时间，这个目前被特判处理了，不需要正则。还有什么场景需要正则嘛

**Comment by SheldonWxy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。

**Comment by SheldonWxy** [comment]
可能是我锄地时候的特殊需求。因为材料上限了，不想捡，所以配置了黑名单，例如：混沌核心、混沌枢纽之类。
一方面是为了配置方便，不需要一个一个材料写入黑名单；另一方面，在实际使用的时候会出现识别出错，例如带上其他玩家的昵称、或者识别成错别字的情况。

**Comment by Alex-Beng** [comment]
那是时序 or 检测精度的问题。因为错别字可能原因：1. f key位置错误导致的。 2. 字处于半透明状态。3. 训练时没有这个词
1是精度问题，2是时序问题，3. 不认识的默认黑名单，不捡，所以不影响。。
现在策略都是比较激进的，例如1. 之前使用轮廓识别f key的方案很稳，但是要等整体浮现，所以改成alpha。2. 没做等待ocr结果稳定再拾取。
所以我都会把东西维持在9970/9999这样，然后用质变仪融掉多的。而且配黑名单可以不用自己输入啊，可以从训练仓库复制，例如[掉落材料](https://github.com/Alex-Beng/yap-train/blob/main/mona/text/material.py)
FYI: #42 #45

**Comment by SheldonWxy** [comment]
好的。
