### ISSUE TITLE
请问黑、白名单优先级

### ISSUE THREAD

**Issue by zhang-weiyu** [Alex-Beng/Yap#8]
请问黑、白名单的读取优先级是怎样的？如果一个物品同时存在于黑名单和白名单，会如何判定？如果一个物品在两个文件中都不存在，是否会拾取？

**Comment by Alex-Beng** [comment]
白名单>黑名单。见：

https://github.com/Alex-Beng/Yap/blob/6d6607e8a215d81d2e872979cbd84efc0db87370/src/pickupper/pickupper.rs#L285-L287

同时存在，在黑名单就会拾取。

都没有，分情况，代码中的`all_list`是训练那个repo导出的。要是训练时的`all_list`有，就会拾取，否则不识字，就不会拾取。
